---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: prakhar-sharma
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "prakharsharma404/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Remove existing container
      shell: docker rm -f calculator || true

    - name: Run Docker container
      shell: docker run -it -d --name calculator prakharsharma404/calculator